--Customer Lifetime Value Analysis---

Select * from customer_data

--Amount of revenue generated by each channel--

Select channel,
sum(revenue) as per_channel_revenue
from customer_data
group by channel
order by per_channel_revenue desc

--Max reveue generated and by which channel--
With max_rev as
(Select channel,
sum(revenue) as per_channel_revenue
from customer_data
group by channel)
Select channel,
per_channel_revenue
from max_rev
where per_channel_revenue=(Select Max(per_channel_revenue) from max_rev)

--

